version: "3"


services:
  veriumd:
    image: buluba89/veriumd:latest
    build:
      context: ./
    #volumes:
      #Mount a local folder for vericoin data.This folder will be used 
      #for storing the blockchain as well as vericoin.conf and your wallet. 
      #- /path/to/data:/data
      #You can copy your wallet in data folder or mount it like this:
      #- /path/to/wallet.dat:/data/wallet.dat
    #This is needed for upnp to work
    network_mode: host
    #Forwarding ports is needed when using swarm mode or not settin 'network_mode:host'
    ports:
     - "36987:36987"
     - "36988:36988"
